# Configuration for the trainer
---

# Dataloader settings
train_dir: ./data/raw/IRMAS_Training_Data

valid_dir: ./data/raw/IRMAS_Validation_Data

# Preprocessing done on raw audio
preprocess: 
  
  PreprocessPipeline:
    parameters:
      target_sr: 22050

# Transforms applied on raw audio after preprocessing
transforms:
  
  Preemphasis:
  
  Spectrogram:
    parameters:
      sample_rate: 22050
      n_mels: 128
      hop_length: 160
      n_fft: 800
  
  LogTransform:
  
  PadCutToLength:
    parameters:
      max_length: 1024
  
  Normalize:
    parameters:
      mean: -4.2677393
      std: 9.1379948
  
transforms_not_used:
- type: FeatureExtractor
  parameters:
    sr: 22050

# Augmentations for spectrograms
signal_augments:
spec_augments:

batch_size: 8

# Training settings

loss:
  
  type: FocalLoss
  parameters:
    alpha: 0.25
    gamma: 2

optimizer:
  
  type: AdamW
  parameters:
    weight_decay: 1.0E-4

learning_rates:
  
  base_model:
    parameters:
      lr: 1.0E-8
  classifier:
    parameters:
      lr: 1.0E-3

# Gradient accumulation
num_accum: 2

verbose: True

EPOCHS: 4

metrics: 
- hamming_score 
- zero_one_score
- mean_average_precision
- mean_f1_score


scheduler:
  
  type: OneCycleLR
  parameters:
    pct_start: 0.3
    anneal_strategy: cos

early_stopping: 
  parameters:
    patience: 3
    min_delta: 0.001

save_best_model: True








