# Configuration for the trainer
---

# Dataloader settings
train_dir: ./data/raw/IRMAS_Training_Data

valid_dir: ./data/raw/IRMAS_Validation_Data

# Preprocessing done on raw audio
preprocess: 
  
  PreprocessPipeline:
    target_sr: 22050

# Transforms applied on raw audio after preprocessing
transforms:
  
  Preemphasis:
  
  Spectrogram:
      sample_rate: 22050
      n_mels: 128
      hop_length: 160
      n_fft: 800
  
  LogTransform:
  
  PadCutToLength:
      max_length: 1024
  
  Normalize:
      mean: -4.2677393
      std: 9.1379948

# Augmentations for spectrograms
signal_augments:
spec_augments:

batch_size: 8

# Training settings
model_name: "MIT/ast-finetuned-audioset-10-10-0.4593"

loss:
  FocalLoss:
      alpha: 0.25
      gamma: 2

optimizer:
  
  AdamW:
      weight_decay: 1.0E-4

learning_rates:
  
  base_model:
      lr: 1.0E-8
  classifier:
      lr: 1.0E-3

# Gradient accumulation
num_accum: 2

verbose: True

EPOCHS: 4

metrics: 
- hamming_score 
- zero_one_score
- mean_average_precision
- mean_f1_score


scheduler:
  
  OneCycleLR:
      pct_start: 0.3
      anneal_strategy: cos

early_stopping:
    patience: 3
    min_delta: 0.0001

save_best_model: True








