version: '3'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile.backend
    ports:
      - "7860:7860"
    networks:
      - deploy_network
    container_name: api
    tty: true
    stdin_open: true

  streamlit:
    build:
      context: .
      dockerfile: DockerFile.frontend
    depends_on:
      - api
    ports:
        - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
