# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

RUN pip install streamlit requests

COPY frontend/ .

EXPOSE 8501

CMD ["streamlit", "run", "ui.py"]

