wandb_version: 1

EPOCHS:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 2
LLRD:
  desc: null
  value:
    base_lr: 0.0001
    lr_decay_rate: 1
    weight_decay: 8.0e-05
    body: base_model
    head: classifier
dropout:
  desc: null
  value: 0.5
num_gpus:
  desc: null
  value: 2
loss:
  desc: null
  value:
    FocalLoss:
      alpha: -1
      gamma: 2
metrics:
  desc: null
  value:
  - hamming_score
  - zero_one_score
  - mAP
  - mean_f1_score
num_accum:
  desc: null
  value: 8
optimizer:
  desc: null
  value:
    AdamW: null
preprocess:
  desc: null
  value:
    PreprocessPipeline:
      target_sr: 16000
save_best_model:
  desc: null
  value: true
scheduler:
  desc: null
  value:
    OneCycleLR:
      anneal_strategy: cos
      pct_start: 0.05
signal_augments:
  desc: null
  value:
    RepeatAudio:
      max_repeats: 6
spec_augments:
  desc: null
  value:
    MaskFrequency:
      max_mask_length: 27
    MaskTime:
      max_mask_length: 165
train_dir:
  desc: null
  value: /nfs/home/8548f215c44990b1/lumen-irmas/data/processed/no_sync_two
transforms:
  desc: null
  value:
    FeatureExtractor:
      sr: 16000
valid_dir:
  desc: null
  value: /nfs/home/8548f215c44990b1/lumen-irmas/data/raw/IRTestingData
verbose:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681162036.731074
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.14.2
      6: 4.27.4
      8:
      - 1
      - 5
