
# Data location
train_dir: ../data/processed/
valid_dir: ..data/raw/

# Fit parameters
epochs: 3
batch_size: 8
num_accum: 4

# Per layer learning rates and weight decay
LLRD:
    base_lr: 2.0e-05
    lr_decay_rate: 0.85
    weight_decay: 8.0e-05
    
    body: base_model
    head: classifier

dropout: 0.5

# Loss function
loss:
    FocalLoss:
      alpha: -1
      gamma: 2

# Metrics
metrics:
  - mean_average_precision

# Optimizer
optimizer:
    AdamW:
      weight_decay: 0

scheduler:
    OneCycleLR:
      anneal_strategy: cos
      pct_start: 0.05

# Data processing
preprocess:
    PreprocessPipeline:
      target_sr: 16000

transforms:
    FeatureExtractor:
      sr: 16000

signal_augments:
    RepeatAudio:
      max_repeats: 6

spec_augments:
    MaskFrequency:
      max_mask_length: 27
    MaskTime:
      max_mask_length: 165


# Settings
num_gpus: 2
verbose: true
save_last_checkpoint: true