
# Data location
train_dir: ../data/processed
valid_dir: ../data/raw/IRTestingData

# Fit parameters
epochs: 3
batch_size: 8
num_accum: 4

# Per layer learning rates and weight decay
LLRD:
    base_lr: 4.3e-6
    lr_decay_rate: 0.8
    weight_decay: 2.3e-3
    
    body: base_model
    head: classifier

dropout: 0.27

# Loss function
loss:
  BCELoss: null

# Metrics
metrics:
  - mean_average_precision

# Optimizer
optimizer:
    AdamW: null

scheduler:
    OneCycleLR:
      anneal_strategy: cos
      pct_start: 0.28

# Data processing
preprocess:
    PreprocessPipeline:
      target_sr: 16000

transforms:
    FeatureExtractor:
      sr: 16000

signal_augments:
    RepeatAudio:
      max_repeats: 6

spec_augments:
    MaskFrequency:
      max_mask_length: 5
    MaskTime:
      max_mask_length: 156

# Settings
num_gpus: 2
verbose: true
save_last_checkpoint: true