
EPOCHS: 3

batch_size: 8
LLRD:
    base_lr: 1.0e-04
    lr_decay_rate: 1
    weight_decay: 8.0e-05

    body: base_model
    head: classifier

dropout: 0.5
num_gpus: 2
loss:
    FocalLoss:
      alpha: -1
      gamma: 2
metrics:
  - hamming_score
  - zero_one_score
  - mAP
  - mean_f1_score
num_accum: 4
optimizer:
    AdamW:
preprocess:
    PreprocessPipeline:
      target_sr: 16000
save_best_model: true
scheduler:
    OneCycleLR:
      anneal_strategy: cos
      pct_start: 0.05
signal_augments:
    RepeatAudio:
      max_repeats: 6
spec_augments:
    MaskFrequency:
      max_mask_length: 27
    MaskTime:
      max_mask_length: 165
train_dir: /nfs/home/8548f215c44990b1/lumen-irmas/data/processed/no_sync_two
transforms:
    FeatureExtractor:
      sr: 16000
valid_dir: /nfs/home/8548f215c44990b1/lumen-irmas/data/raw/IRTestingData
verbose: true