
# Data location
train_dir: ../data/processed/ensemble
valid_dir: ../data/raw/IRTestingData

# Fit parameters
epochs: 2
batch_size: 8
num_accum: 4

# Per layer learning rates and weight decay
LLRD:
    base_lr: 1.0e-3
    lr_decay_rate: 1
    weight_decay: 0
    
    body: base_model
    head: classifier

dropout: 0.27

# Loss function
loss:
  BCELoss: null

# Metrics
metrics:
  - mean_average_precision

# Optimizer
optimizer:
    AdamW:
      weight_decay: 0

scheduler:
    OneCycleLR:
      anneal_strategy: cos
      pct_start: 0.28

# Data processing
preprocess:
    PreprocessPipeline:
      target_sr: 16000

transforms:
    FeatureExtractor:
      sr: 16000

signal_augments:
    RepeatAudio:
      max_repeats: 6

spec_augments:
    MaskFrequency:
      max_mask_length: 5
    MaskTime:
      max_mask_length: 156


# Settings
num_gpus: 1
verbose: true
save_last_checkpoint: true