early_terminate:
  eta: 2
  min_iter: 3
  type: hyperband
method: bayes
metric:
  goal: maximize
  name: mAP
parameters:
  EPOCHS:
    distribution: int_uniform
    max: 4
    min: 2
  LLRD:
    parameters:
      base_lr:
        distribution: log_uniform_values
        max: 0.001
        min: 5e-06
      lr_decay_rate:
        distribution: uniform
        max: 1
        min: 0.75
      weight_decay:
        distribution: log_uniform_values
        max: 0.01
        min: 1e-08
  batch_size:
    value: 8
  dropout:
    distribution: uniform
    max: 0.8
    min: 0.1
  loss:
    parameters:
      FocalLoss:
        parameters:
          alpha:
            values:
              - -1
              - 0.25
              - 0.5
              - 0.75
          gamma:
            values:
              - 1
              - 2
              - 3
  metrics:
    value:
      - hamming_score
      - zero_one_score
      - mAP
      - mean_f1_score
  num_accum:
    value: 4
  optimizer:
    parameters:
      AdamW:
        parameters:
          weight_decay:
            value: 0
  preprocess:
    parameters:
      PreprocessPipeline:
        parameters:
          target_sr:
            value: 16000
  save_best_model:
    value: true
  scheduler:
    parameters:
      OneCycleLR:
        parameters:
          anneal_strategy:
            value: cos
          pct_start:
            distribution: uniform
            max: 0.3
            min: 0.05
  signal_augments:
    parameters:
      RepeatAudio:
        parameters:
          max_repeats:
            distribution: int_uniform
            max: 6
            min: 3
  spec_augments:
    parameters:
      MaskFrequency:
        parameters:
          max_mask_length:
            distribution: int_uniform
            max: 30
            min: 10
      MaskTime:
        parameters:
          max_mask_length:
            distribution: int_uniform
            max: 200
            min: 50
  train_dir:
    value: ./data/processed/pitch_sync/IRMAS_Training_Data
  transforms:
    parameters:
      FeatureExtractor:
        parameters:
          sr:
            value: 16000
  valid_dir:
    value: ./data/raw/IRMAS_Validation_Data
  verbose:
    value: true